[camera]
position = [0.0, 0.0, 3.0]
target = [0.0, 0.0, 0.0]

[[lights]]
position = [0.0, 0.0, 3.0]
diffuse_color = [1.0, 1.0, 1.0]

[[objects]]
mesh = "objects/ball/ball.obj"
scale = [1.0, 1.0, 1.0]
orientation = [0.0, 0.0, 0.0]
position = [0.0, 0.0, 0.0]

[objects.update]
orientation = [0.008, 0.008, 0.012]

