[camera]
position = [0.0, 0.0, 5.0]
target = [0.0, 0.0, 0.0]

[[lights]]
position = [0.0, 0.0, 5.0]

[[objects]]
mesh = "objects/colors/colors.obj"

[objects.update]
orientation = [0.008, 0.008, 0.012]
