[camera]
position = [0.0, 0.0, -3.0]
target = [0.0, 0.0, 0.0]

[[lights]]
diffuse_color = [1.0, 0.0, 0.0]
position = [-5.0, -5.0, -5.0]

[[lights]]
diffuse_color = [0.0, 1.0, 0.0]
position = [5.0, -5.0, -5.0]

[[lights]]
diffuse_color = [0.0, 0.0,11.0]
position = [5.0, 5.0, -0.0]

[[lights]]
diffuse_color = [1.0, 0.0, 1.0]
position = [-5.0, 5.0, -0.0]

[[objects]]
mesh = "objs/cube.obj"
scale = [1.0, 1.0, 1.0]
orientation = [0.0, 0.0, 0.0]
position = [0.0, 0.0, 0.0]

[objects.update]
orientation = [0.005, 0.005, 0.0075]
