[camera]
position = [0.0, 0.0, 4.0]
target = [0.0, 0.0, 0.0]

[[lights]]
position = [0.0, 0.0, 5.0]
diffuse_color = [1.0, 1.0, 1.0]
specular_color = [0.5, 0.5, 0.5]

[[objects]]
mesh = "objects/dice/dice.obj"
scale = [0.6, 0.6, 0.6]
orientation = [0.0, 0.0, 0.0]
position = [-0.9, -0.3, 0.0]

[objects.update]
orientation = [0.8, 1.4, 0.0]

[[objects]]
mesh = "objects/dice/dice.obj"
scale = [0.6, 0.6, 0.6]
orientation = [0.0, 0.0, 0.0]
position = [0.9, 0.3, 0.0]

[objects.update]
orientation = [-0.8, -1.4, 0.0]
