ambient_color = [1.0, 1.0, 1.0]

[camera]
position = [0.0, 0.0, -3.5]
target = [0.0, 0.0, 0.0]

[[lights]]
position = [0.0, 0.0, -5.0]
diffuse = [0.7, 0.5, 0.2]
specular = [0.0, 0.0, 0.0]

[[lights]]
position = [0.0, 0.0, -5.0]
diffuse = [0.7, 0.7, 0.7]
specular = [1.0, 1.0, 1.0]

[[objects]]
mesh = "objs/nefertiti.obj"
scale = [1.0, 1.0, 1.0]
orientation = [0.0, 0.0, 0.0]
position = [0.0, 0.0, 0.0]

[objects.material]
ambient = [0.0, 0.0, 0.0]
diffuse = [0.5, 0.5, 0.5]
specular = [0.3, 0.3, 0.3]
shininess = 50.0

[objects.update]
orientation = [0.0, 0.008, 0.0]
