ambient_color = [1.0, 1.0, 1.0]

[camera]
position = [0.0, 0.0, 3.5]
target = [0.0, 0.0, 0.0]

[[lights]]
position = [0.0, 0.0, 5.0]
diffuse_color = [0.9, 0.75, 0.5]
specular_color = [1.0, 1.0, 1.0]

[[objects]]
mesh = "objs/nefertiti.obj"
scale = [1.0, 1.0, 1.0]
orientation = [0.0, 0.0, 0.0]
position = [0.0, 0.0, 0.0]

[objects.material]
ambient_component = [0.0, 0.0, 0.0]
diffuse_component = [0.7, 0.7, 0.7]
specular_component = [0.3, 0.3, 0.3]
specular_exponent = 100

[objects.update]
orientation = [0.0, 0.008, 0.0]
