[camera]
position = [0.0, 0.0, 3.5]
target = [0.0, 0.0, 0.0]

[[lights]]
position = [0.0, 0.0, 5.0]
diffuse_color = [0.9, 0.75, 0.5]
specular_color = [1.0, 1.0, 1.0]

[[objects]]
mesh = "objects/nefertiti/nefertiti.obj"
scale = [1.0, 1.0, 1.0]
orientation = [0.0, 0.0, 0.0]
position = [0.0, 0.0, 0.0]

[objects.update]
orientation = [0.0, 0.008, 0.0]
