[camera]
position = [0.0, 0.0, 3.5]
target = [0.0, 0.0, 0.0]

[[lights]]
diffuse_color = [0.3, 0.5, 0.7]
specular_color = [1.0, 1.0, 1.0]
position = [0.0, 0.0, 5.0]

[[objects]]
mesh = "objs/torus-flat.obj"
scale = [1.0, 1.0, 1.0]
orientation = [0.0, 0.0, 0.0]
position = [0.0, 0.0, 0.0]

[objects.material]
diffuse_component = [1.0, 1.0, 1.0]
specular_component = [0.3, 0.3, 0.3]
specular_exponent = 40

[objects.update]
orientation = [0.008, 0.008, 0.012]
