[camera]
position = [0.0, 0.0, 3.5]

[[lights]]
diffuse_color = [0.3, 0.5, 0.7]
specular_color = [1.0, 1.0, 1.0]
position = [0.0, 0.0, 5.0]

[[objects]]
mesh = "objects/torus/torus-smooth.obj"

[objects.update]
orientation = [0.8, 1.4, 0.0]
